steps:
  - id: 'Rodando docker-compose'
    name: 'docker/compose'
    args: ['-f', 'docker-compose.prod.yaml', 'up', '-d', 'app', 'elasticsearch']

  - id: 'Esperando elasticsearch'
    name: 'docker/compose'
    args:
      [
        'run',
        'dockerize',
        'dockerize',
        '-wait',
        'http://elasticsearch:9200',
        '-wait',
        'http://app:3001',
        '-timeout',
        '120s',
      ]

  - id: 'Rodando tests'
    name: 'docker'
    args: ['exec', '-t', 'app', 'npm', 'test']

  - id: 'Rodando build'
    name: 'docker'
    args: ['exec', '-t', 'app', 'npm', 'build']
